# Generated by Django 4.0 on 2021-12-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-timestamp']},
        ),
    ]
